version: '2.1'

networks:
  monitor-net:
    driver: bridge

services:         
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
            # - PUID=1001
            #      - PGID=1001
      - TZ=America/New_York
        #- SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
        #ss- INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - ./config:/config
      - ./modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
