version: '2.1'

networks:
  monitor-net:
    driver: bridge

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

#  nginx:
#   image: linuxserver/nginx
#    container_name: nginx
#    environment:
#      - PUID=1001
#      - PGID=1001
#      - TZ=America/New_York
#    volumes:
#      - ./nginx_config:/config
#      - ./config:/config/www/wgconfig
#    ports:
#      - 8088:80
#      - 4435:443
#    depends_on:
#      - wireguard
#    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8098:80/tcp
      - 4436:443/tcp
    environment:
      TZ: America/New_York
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  wg-gui:
    container_name: wg_gui
    image: embarkstudios/wireguard-ui:latest
    entrypoint: /wireguard-ui
    privileged: true
    environment:
      - PUID=1001
      - PGID=1001
      - WIREGUARD_UI_CLIENT_IP_RANGE=192.168.89.0/24
      - WIREGUARD_UI_WG_ENDPOINT=home.ryanpampush.com:51820
      - WIREGUARD_UI_WG_ALLOWED_IPS=0.0.0.0/0
      - WIREGUARD_UI_WG_DNS=10.37.70.7
    ports:
      - 8080:8080
      - 5555:5555
    volumes:
      - ./wg-gui/:/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
