version: '2.1'

networks:
  monitor-net:
    driver: bridge

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8098:80/tcp
      - 4436:443/tcp
    environment:
      TZ: America/New_York
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  subspace:
    image: pushc6/subspace:latest
    container_name: subspace
    volumes:
      - /opt/docker/subspace:/data
    restart: unless-stopped
    environment:
      - PGID=1001
      - PUID=1001
      - SUBSPACE_HTTP_HOST=$vpnip
      - SUBSPACE_LETSENCRYPT=false
      - SUBSPACE_HTTP_INSECURE=true
      - SUBSPACE_HTTP_ADDR=":80"
      - SUBSPACE_NAMESERVER=127.0.0.1
      - SUBSPACE_LISTENPORT=51820
      - SUBSPACE_IPV4_POOL=10.99.97.0/24
      - SUBSPACE_IPV4_GW=10.99.97.1
      - SUBSPACE_IPV6_NAT_ENABLED=0    
      - SUBSPACE_DNSMASQ_DISABLED=1
    cap_add:
      - NET_ADMIN
    network_mode: "host"
